### PR TITLE
Make indentation consistent

### PR DESCRIPTION
**Pull request by danielkrupinski**

### CODE REVIEW

**Comment by zxvnme** [comment]
Code was formatted by IDE during commiting changes to repository via JetBrains VCS.

**Comment by danielkrupinski** [comment]
[Reference](https://lintlyci.github.io/Flake8Rules/rules/E111.html)

**Comment by cyanidee** [comment]
1. The code was initially yours, doesn't matter though, but you could've formatted it when pushing.
2. The code style is a **personal preference**, it is not written anywhere that all code written in Python **has to follow these guidelines** (on the reference you linked its even stated: _PEP8 recommends that Python code indentation be a multiple of four._).

**Comment by danielkrupinski** [comment]
My initial code has consistent 4 space indentation - https://gist.github.com/danielkrupinski/02ffcbd7a2bc45eeb8ef648f8a80768c

**Comment by cyanidee** [comment]
> My initial code has consistent 4 space indentation - https://gist.github.com/danielkrupinski/02ffcbd7a2bc45eeb8ef648f8a80768c

Okay, my bad, the code was re-formatted while pushing to the repository thanks to Jetbrains IDE, what's your thoughts on the 2nd point though?

**Comment by danielkrupinski** [comment]
PEP8 style guide are widely accepted by Python programmers and 4 space indentation is nearly standard indentation for Python scripts. Nonetheless it's up to you to write consequent code following good practices.

**Pull request closed without merging**
